# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/ft5726/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt8173/include/

obj-y += focaltech_driver.o
obj-y += focaltech_ex_fun.o
obj-y += focaltech_ctl.o

obj-y += Config_FT5822.o
obj-y += DetailThreshold.o
obj-y += Global.o ini.o
obj-y += Test_FT5822.o
obj-y += test_lib.o
